# Setup
title: TacitVenom
tagline: "Personal Website"
description: "My personal website and blog."
url: https://tacitvenom.github.io
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: TacitVenom
  url: https://github.com/tacitvenom

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
